addrating/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('show/<int:landlord_id>', views.show_reviews, name='show_rev'),
    path('<int:landlord_id>', views.addreview, name='review'),
]

landlord/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('', views.search, name='search'),
    path('add/', views.addlandlord, name='add'),
]

ratemylandlord/urls.py
from django.contrib import admin
from django.urls import path, include

# from addrating.views import *
app_name = 'ratemylandlord'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landlord.urls')),
    path('addrating/', include(('addrating.urls', 'ratemylandlord'), namespace='addrating')),
    path('landlord/', include(('landlord.urls', 'ratemylandlord'), namespace='landlord')),
]

addrating/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.forms import ModelForm

# Create your models here.
from landlord.models import Landlord

RATING = [
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
]
BINARY = [
    (False, 'No'),
    (True, 'Yes')
]
class Review(models.Model):

    fixing_rate = models.IntegerField(choices=RATING)
    liveable_cond = models.IntegerField(choices=RATING)
    review = models.TextField(max_length=1000, null=False)
    take_again = models.BooleanField(choices=BINARY)
    landlord = models.ForeignKey(Landlord, on_delete=models.CASCADE, null=True)

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['fixing_rate', 'liveable_cond', 'take_again','review', 'landlord']

landlord/models.py
from django.db import models
from address.models import AddressField
from django.forms import ModelForm, TextInput, forms

class Search(models.Model):
    address = AddressField(on_delete=models.CASCADE)

class SearchForm(ModelForm):
    class Meta:
        model  = Search
        fields = ['address']

class Landlord(models.Model):
    first_name = models.CharField(help_text="First name",max_length=50)
    last_name = models.CharField(help_text="Last Name",max_length=50)
    address = AddressField(on_delete=models.CASCADE)

    def __str__(self):
        context = ""
        context += self.first_name + " "
        context += self.last_name + " "
        context += self.address.raw
        return context

class LandlordForm(ModelForm):
    class Meta:
        model = Landlord
        fields = ['first_name', 'last_name', 'address']

addrating/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from addrating.models import *
from django.http import HttpResponse
from django.contrib import messages
from landlord.models import LandlordForm
from django.db.models import Avg

def addreview(request, landlord_id):
    print("we're in addreview function")
    landlord = Landlord.objects.get(id=landlord_id)

    if request.method == 'GET':
            form = ReviewForm()
            return render(request, 'addreview.html', {'form': form, 'landlord':landlord})
    else:
        review = Review()
        review.fixing_rate = request.POST['fixing_rate']
        review.liveable_cond = request.POST['liveable_cond']
        review.review = request.POST['review']
        review.landlord = landlord
        review.take_again = request.POST['take_again']
        review.save()
        messages.success(request, 'Thank you for your review')
        return show_reviews(request, landlord_id)

def show_reviews(request, landlord_id, ):
    print("we're in show reviews function")
    landlord = Landlord.objects.get(id=landlord_id)
    reviews = Review.objects.filter(landlord_id=landlord_id)
    avg = Review.objects.filter(landlord_id=landlord_id).aggregate(a =( Avg('fixing_rate')+ Avg('liveable_cond'))/2)
    return render(request, 'reviews.html', {'reviews': reviews, 'landlord':landlord, 'avg':avg})

landlord/views.py
from address.forms import AddressField
from address.models import Address
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from addrating.models import Review
from landlord.models import *
from django.contrib import messages



def search(request):
    form = SearchForm()
    print(request.POST.items())
    if request.method == "POST":
        search_term = SearchForm(request.POST)
        landlords = Landlord.objects.filter(address__raw__contains=search_term.data['address'])
        if len(landlords) != 0:
            return render(request, 'landlord/search_results.html', {'form':form,'landlords': landlords})
        else:
            messages.add_message(request, messages.WARNING, 'No landlord was added at this address. You can click on Add Landlord to add one.')
            return redirect('landlord:search')
    else:
        landlords = Landlord.objects.all()
        l = len(landlords)
        landlords = landlords[(l-3):]
        list = []
        for x in range(len(landlords)):
            r = Review.objects.filter(landlord_id=landlords[x].id)[0].review
            list.append(r)

        return render(request, 'landlord/search.html', {'form':form, 'landlords':landlords, 'list':list})

def addlandlord(request):

    if request.method == 'POST':
        landlord_instance = LandlordForm(request.POST)
        exists = Landlord.objects.filter(address__raw=landlord_instance.data['address']).exists()
        if exists:
            messages.error(request, 'This landlord already exists in our database')
            return redirect('landlord:add')
        else:
            landlord_instance.save()
            id   = Landlord.objects.filter(address__raw=landlord_instance.data['address']).values('id')[0]['id']
            messages.success(request, 'Succesfully added landlord')
            return redirect('addrating:review', landlord_id=id)  # will send get request
    else:
        print("trying to add landlord")
        form = LandlordForm()
        return render(request, 'landlord/addlandlord.html', {'form': form})

addrating/templates/addreview.html
{% extends 'landlord/base.html' %}

<head>
    {% block title %}
    Add Review
    {% endblock %}
</head>

{% block content %}
<style>
    table{
        width: 50%;
    }
    th, td {
      padding: 5px;
      text-align: left;
    }
    #field{
        text-align:right;
    }
    button{
        border: 1px solid black;
        background-color: black;
        color: white;
    }

</style>
<body>
<h2 class="w3-display-topmiddle" style="border: 1px solid black; width: 14%; padding-left: 1%;margin-top:1%">Add Review</h2>
<form method="post" class="w3-container w3-display-middle w3-padding-60 w3-margin-top" style="margin-left: 7px;">

        <h3>{{landlord.last_name}} {{landlord.first_name}}</h3>
        <h3>{{landlord.address.raw}}</h3>

        {% csrf_token %}
        {% for field in form %}
            <table>
                {% if forloop.counter <= 4 %}
                <tr>
                        <th>{{field.label_tag}} </th>
                        <td id="field">{{field}}</td>
                </tr>
                {% endif %}
            </table>
        {% endfor %}

             <input type="hidden" name="landlord" value="{{landlord}}">
        <button  type="submit" >Submit</button>
    </form>
</body>
{% endblock %}

addrating/templates/reviews.html
{% extends 'landlord/base.html' %}

<head>
    {% block title %}
    Reviews
    {% endblock %}
</head>

{% block content %}

<style>
    table{
        width: 100%;
    }
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
    th, td {
      padding: 5px;
      text-align: left;
    }
    input{
        background-color:white;
    }
    input:hover{
        background-color: black;
        color:white;
    }
    .center{
      margin-left: 23%;
      margin-right: 23%;
      margin-top: 60px;
    }
    #land_title{
        background-color: white;
        color:black;
        margin-top: 30px;
        margin-bottom: 20px;
    }
</style>

<body >
    <div id="container"  class="center">
        <div id="land_title" >
            <h3>{{landlord.first_name}}, {{landlord.last_name}} <br> {{landlord.address.raw}}</h3>
            <h2> {{avg.a}}/5 </h2>
            <form action="{% url 'addrating:review' landlord.id %}">
                <input type="submit" value="Add Review"/>
            </form>
        </div>

        <div id="reviews" >
            {% for review in reviews %}
            <table >
                <tr>
                    <td> <strong> Fixing rate:           </strong> {{review.fixing_rate}}/5  </td>
                    <td> <strong> Liveable conditions :  </strong> {{review.liveable_cond}}/5</td>
                    <td> <strong> Would take again:      </strong>
                        {% if review.take_again %}
                        Yes
                        {% else %}
                        No
                        {% endif%}
                    </td>
                </tr>
                <tr>
                    <td colspan="3"> <strong> Review: </strong>{{review.review}}</td>
                </tr>
            </table>
            <br>
            {% endfor %}
        </div>
    </div>
</body>
{% endblock %}

landlord/templates/landlord/addlandlord.html
{% extends 'landlord/base.html' %}
{% block content %}
<head>
    {{ form.media }} <!-- needed for JS/GoogleMaps lookup -->
</head>

<style>

button{
    margin: 10px 0px 0px 77%;
    background-color: black;
    border: 1px solid white;
    color: white;
}

#title{
    border: 1px solid black;
    width: 16.9%;
    margin-top: 8%;
}
#field{
    text-align: left;
}


</style>

    <h2 id="title" class="w3-display-topmiddle w3-padding-large">Add Landlord</h2>
    <form method="post" class="w3-large w3-display-middle"  >

        {% csrf_token %}
        <table>
        {% for field in form %}

                {% if forloop.counter < 4 %}
                <tr>
                        <th>{{field.label_tag}} </th>
                        <td id="field">{{field}}</td>
                </tr>
                {% endif %}
              {% endfor %}
            </table>
        <button type="submit">Submit</button>
    </form>
{% endblock %}

landlord/templates/landlord/base.html
<!DOCTYPE html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

    <title>{% block title %}RateMyLandlord{% endblock %}</title>

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</head>

<style>

body, html {height: 100%}
.bgimg {
  background-image:  url('{% static 'city2.jpg' %}');
  min-height: 100%;
  background-position: center;
  background-size: cover;
}
.topbox{
    background-color: black;
    color: white;
    padding: 5px;
    text-decoration: none;
}
.topbox:hover{
    text-decoration: underline;
}

</style>

<body>

    <div>
        {% if messages %}
        {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fixed-bottom" role="alert" style="margin: 0 40px 0 1px;">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        {% endif %}

        <div class="w3-display-topleft w3-padding-large w3-xlarge">
            <a href="{% url 'landlord:search' %}" class="topbox">Search</a>
            <a href="{% url 'add' %}" class="topbox">Add Landlord</a>
        </div>

        <div class="topbox w3-display-topright w3-padding-small w3-xlarge"
              style="margin: 10px 20px 0 0; border: 2px solid white;">Rate My Landlord </div>

        <div id="content" name="content" >
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>

</html>

landlord/templates/landlord/search.html
{% extends 'landlord/base.html' %}
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>

    {{form.media}}

</head>

<style>

    button{
        background-color: black;
        position: relative;
        left: 100%;
        bottom: 40px;
        color: white;
        height: 40px;
  	    border-radius: 26px;
	    border:5px solid black;
	    margin-left: 5px;
    }
    table{
        width: 100%;
    }
    th, td {
      padding: 7px;
      text-align: left;
      border-style:solid;
      border-width: 1px;
      border-color:black;
    }
    .review{
      background-color:white;

    }
    input{
        w
    }
    input[type=text]{
        border: 1px solid black;
        border-radius: 10px;
        height: 40px;
        padding: 3px 10px 3px 10px;
        color: black;
        font-family:  Arial, Helvetica, sans-serif;
        width: 450px;
    }
    input[type=text]:focus{
        border: 3px solid #2E0014;
    }

</style>

<body>

    <div class="w3-display-topmiddle w3-padding-large">
        <div style="width:72%; margin-left: 8%;">
            <form method="post">
               {% csrf_token %}
               {{form.address}}
                <button type="submit">Search</button>
            </form>
        </div>


        <h2 style="margin-bottom: 15px">Latest Results</h2>
        <div id="reviews" >
            {% for landlord in landlords %}
            <table class="review">
                <tr>
                    <td style="font-size: 19px;"> <strong> {{landlord.first_name}} {{landlord.last_name}}</strong> </td>
                </tr>
                <tr>
                   {% for l in list %}
                      {% if forloop.counter == forloop.parentloop.counter %}
                         <td> <strong> Review:  </strong> {{l}}</td>
                      {% endif %}
                   {% endfor %}
                </tr>
            </table>
            <br>
            {% endfor %}
        </div>
    </div>

</body>

{% endblock %}
</html>

landlord/templates/landlord/search_results.html
{% extends 'landlord/base.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="UTF-8">
    <title>Search</title>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
</head>
<style>

body{
<!--    background-image:  url('{% static 'city2.jpg' %}');-->
<!--    min-height: 100%;-->
<!--    background-position: absolute center;-->
<!--    background-size: cover;-->
}
 .result{
    background-color: black;
    color : white;
    padding: 10px;
    font-size: large;
    text-decoration: none;
 }
 .result:hover{
    background-color: white;
    color: black;
    text-decoration: underline;
    border-style: solid;
 }
 .address{
    background-color: black;
    color: white;
    margin-top: 6%;
    font-size: xxx-large;
    padding-left: 1%;
    padding-right: 1%;
 }

</style>
<body>

<div class="w3-display-topmiddle address">
    Results
</div>

    <div class=" w3-display-middle result" >
        {% for landlord in landlords%}
            {% csrf_token %}
            <a href="{% url 'addrating:show_rev' landlord.id %}" > {{landlord}}</a>
    </div>
    {% endfor %}

</body>

{% endblock %}